"""Initial schema

Revision ID: 05afb2822af4
Revises: 
Create Date: 2026-03-31 09:48:51.630756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05afb2822af4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_email'), 'hr', ['email'], unique=True)
    op.create_index(op.f('ix_hr_id'), 'hr', ['id'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('jd_dict_json', sa.JSON(), nullable=True),
    sa.Column('weights_json', sa.JSON(), nullable=True),
    sa.Column('qualify_score', sa.Float(), nullable=False),
    sa.Column('min_academic_percent', sa.Float(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('project_question_ratio', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('education_requirement', sa.String(length=50), nullable=True),
    sa.Column('experience_requirement', sa.Integer(), nullable=False),
    sa.Column('custom_questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_created_at'), 'job_descriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_descriptions_id'), 'job_descriptions', ['id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_uid', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('resume_path', sa.String(length=300), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('parsed_resume_json', sa.JSON(), nullable=True),
    sa.Column('selected_jd_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['selected_jd_id'], ['job_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_candidate_uid'), 'candidates', ['candidate_uid'], unique=True)
    op.create_index(op.f('ix_candidates_created_at'), 'candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_selected_jd_id'), 'candidates', ['selected_jd_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('jd_title', sa.String(length=150), nullable=True),
    sa.Column('jd_text', sa.String(), nullable=True),
    sa.Column('skill_scores', sa.JSON(), nullable=True),
    sa.Column('gender_requirement', sa.String(length=50), nullable=True),
    sa.Column('education_requirement', sa.String(length=50), nullable=True),
    sa.Column('experience_requirement', sa.Integer(), nullable=True),
    sa.Column('cutoff_score', sa.Float(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('custom_questions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['hr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('shortlisted', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('interview_date', sa.String(), nullable=True),
    sa.Column('interview_link', sa.String(), nullable=True),
    sa.Column('interview_questions', sa.JSON(), nullable=True),
    sa.Column('interview_token', sa.String(), nullable=True),
    sa.Column('events_json', sa.JSON(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('stage_updated_at', sa.DateTime(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown_json', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('hr_decision', sa.String(length=20), nullable=True),
    sa.Column('hr_final_score', sa.Float(), nullable=True),
    sa.Column('hr_behavioral_score', sa.Float(), nullable=True),
    sa.Column('hr_communication_score', sa.Float(), nullable=True),
    sa.Column('hr_notes', sa.Text(), nullable=True),
    sa.Column('hr_red_flags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_result_candidate_job')
    )
    op.create_index(op.f('ix_results_application_id'), 'results', ['application_id'], unique=True)
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    op.create_index(op.f('ix_results_stage'), 'results', ['stage'], unique=False)
    op.create_table('application_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_by_role', sa.String(length=20), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_stage_history_created_at'), 'application_stage_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_application_stage_history_id'), 'application_stage_history', ['id'], unique=False)
    op.create_index(op.f('ix_application_stage_history_result_id'), 'application_stage_history', ['result_id'], unique=False)
    op.create_index(op.f('ix_application_stage_history_stage'), 'application_stage_history', ['stage'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('per_question_seconds', sa.Integer(), nullable=False),
    sa.Column('total_time_seconds', sa.Integer(), nullable=False),
    sa.Column('remaining_time_seconds', sa.Integer(), nullable=False),
    sa.Column('max_questions', sa.Integer(), nullable=False),
    sa.Column('baseline_face_signature', sa.Text(), nullable=True),
    sa.Column('baseline_face_captured_at', sa.DateTime(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_violation_frames', sa.Integer(), nullable=False),
    sa.Column('paused_until', sa.DateTime(), nullable=True),
    sa.Column('llm_eval_status', sa.String(length=20), nullable=False),
    sa.Column('evaluation_summary_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_candidate_id'), 'interview_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_result_id'), 'interview_sessions', ['result_id'], unique=False)
    op.create_table('interview_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_questions_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('focus_skill', sa.String(length=80), nullable=True),
    sa.Column('project_name', sa.String(length=160), nullable=True),
    sa.Column('reference_answer', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_summary', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('allotted_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('llm_feedback', sa.Text(), nullable=True),
    sa.Column('evaluation_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_v2_id'), 'interview_questions_v2', ['id'], unique=False)
    op.create_index(op.f('ix_interview_questions_v2_session_id'), 'interview_questions_v2', ['session_id'], unique=False)
    op.create_table('proctor_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proctor_events_created_at'), 'proctor_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_proctor_events_id'), 'proctor_events', ['id'], unique=False)
    op.create_index(op.f('ix_proctor_events_session_id'), 'proctor_events', ['session_id'], unique=False)
    op.create_table('interview_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('time_taken_sec', sa.Integer(), nullable=False),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('llm_feedback', sa.Text(), nullable=True),
    sa.Column('evaluation_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions_v2.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_answers_id'), 'interview_answers', ['id'], unique=False)
    op.create_index(op.f('ix_interview_answers_question_id'), 'interview_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_interview_answers_session_id'), 'interview_answers', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_answers_session_id'), table_name='interview_answers')
    op.drop_index(op.f('ix_interview_answers_question_id'), table_name='interview_answers')
    op.drop_index(op.f('ix_interview_answers_id'), table_name='interview_answers')
    op.drop_table('interview_answers')
    op.drop_index(op.f('ix_proctor_events_session_id'), table_name='proctor_events')
    op.drop_index(op.f('ix_proctor_events_id'), table_name='proctor_events')
    op.drop_index(op.f('ix_proctor_events_created_at'), table_name='proctor_events')
    op.drop_table('proctor_events')
    op.drop_index(op.f('ix_interview_questions_v2_session_id'), table_name='interview_questions_v2')
    op.drop_index(op.f('ix_interview_questions_v2_id'), table_name='interview_questions_v2')
    op.drop_table('interview_questions_v2')
    op.drop_table('interview_feedbacks')
    op.drop_index(op.f('ix_interview_sessions_result_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_candidate_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_application_stage_history_stage'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_result_id'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_id'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_created_at'), table_name='application_stage_history')
    op.drop_table('application_stage_history')
    op.drop_index(op.f('ix_results_stage'), table_name='results')
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_index(op.f('ix_results_application_id'), table_name='results')
    op.drop_table('results')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_candidates_selected_jd_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_created_at'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_candidate_uid'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_job_descriptions_id'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_created_at'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_hr_id'), table_name='hr')
    op.drop_index(op.f('ix_hr_email'), table_name='hr')
    op.drop_table('hr')
    # ### end Alembic commands ###
